CREATE TABLE CLIENTE (
    ID INTEGER NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CEP CHAR(10) NOT NULL,
    LOGRADOURO VARCHAR(60) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(40) NOT NULL,
    CIDADE VARCHAR(40) NOT NULL,
    IBGE_CIDADE VARCHAR(7) NOT NULL,
    SIGLA_UF CHAR(2) NOT NULL,
    IBGE_UF CHAR(2) NOT NULL)
		
ALTER TABLE CLIENTE
ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (ID)

CREATE TABLE CONTATO (
    ID INTEGER NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DATA_NASC TIMESTAMP,
    IDADE INTEGER,
    TELEFONE VARCHAR(15),
    ID_CLIENTE INTEGER)
		
ALTER TABLE CONTATO
ADD CONSTRAINT PK_CONTATO
PRIMARY KEY (ID)

ALTER TABLE CONTATO
ADD CONSTRAINT FK_CONTATO_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(ID)

