/******************************************************************************/
/*           Generated by IBExpert 2021.2.16.1 31/05/2021 23:02:16            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

SET CLIENTLIB 'fbclient.dll';

CREATE DATABASE 'C:\_Dev\MicroData-Test\Database\DB.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;



/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_CLIENTE_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_CLIENTE_ID TO 0;

CREATE GENERATOR GEN_CONTATO_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_CONTATO_ID TO 0;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE CLIENTE (
    ID           INTEGER NOT NULL,
    NOME         VARCHAR(50) NOT NULL,
    CEP          CHAR(10) NOT NULL,
    LOGRADOURO   VARCHAR(60) NOT NULL,
    NUMERO       VARCHAR(10) NOT NULL,
    COMPLEMENTO  VARCHAR(40) NOT NULL,
    CIDADE       VARCHAR(40) NOT NULL,
    IBGE_CIDADE  CHAR(7) NOT NULL,
    SIGLA_UF     CHAR(2) NOT NULL,
    IBGE_UF      CHAR(2) NOT NULL
);

CREATE TABLE CONTATO (
    ID          INTEGER NOT NULL,
    NOME        VARCHAR(50) NOT NULL,
    DATA_NASC   TIMESTAMP,
    IDADE       INTEGER,
    TELEFONE    VARCHAR(15),
    ID_CLIENTE  INTEGER
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (ID);
ALTER TABLE CONTATO ADD CONSTRAINT PK_CONTATO PRIMARY KEY (ID);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE CONTATO ADD CONSTRAINT FK_CONTATO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: CLIENTE_BI */
CREATE TRIGGER CLIENTE_BI FOR CLIENTE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_cliente_id,1);
end
^

/* Trigger: CONTATO_BI */
CREATE TRIGGER CONTATO_BI FOR CONTATO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_contato_id,1);
end
^

/* Trigger: CONTATO_BIU0 */
CREATE TRIGGER CONTATO_BIU0 FOR CONTATO
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
  declare variable idade integer;

  declare variable DiaAtual integer;
  declare variable MesAtual integer;
  declare variable AnoAtual integer;

  declare variable DiaNasc integer;
  declare variable MesNasc integer;
  declare variable AnoNasc integer;
begin
if ((new.data_nasc <> old.data_nasc) or (old.data_nasc is null)) then
  begin
    DiaAtual = extract(day from current_timestamp);
    MesAtual = extract(month from current_timestamp);
    AnoAtual = extract (year from current_timestamp);

    DiaNasc = extract(day from new.data_nasc);
    MesNasc = extract(month from new.data_nasc);
    AnoNasc = extract(year from new.data_nasc);

    idade = anoatual - AnoNasc;
    if ((MesAtual < MesNasc) or ((MesAtual = MesNasc) and (diaatual < dianasc))) then
      idade = idade -1;

    new.idade = idade;
  end
end
^
SET TERM ; ^



INSERT INTO cliente (id, nome, cep, logradouro, numero, complemento, cidade, ibge_cidade, sigla_uf, ibge_uf)
VALUES ((select coalesce(max(cliente.id),0)+1 from cliente),'MICRODATA SISTEMAS','37471-140','Avenida Nove de Julho','562','Empresa de Software','Americana','3501608','SP','SP');

INSERT INTO contato (id, nome, data_nasc, telefone, id_cliente)
VALUES ((select coalesce(max(contato.id),0)+1 from contato),'Rafael Araújo','01.01.1985','(19) 97118-2001',1);

INSERT INTO contato (id, nome, data_nasc, telefone, id_cliente)
VALUES ((select coalesce(max(contato.id),0)+1 from contato),'Joelton Lino Luz','10.09.1990','(35) 98717-0737',1);

INSERT INTO contato (id, nome, data_nasc, telefone, id_cliente)
VALUES ((select coalesce(max(contato.id),0)+1 from contato),'Jorge Caldas','20.04.1982','(35) 99999-1234',1);